parameters:
#    fulgurio_media_library_manager.example.class: Fulgurio\MediaLibraryManagerBundle\Example

services:
#    fulgurio_media_library_manager.example:
#        class: %fulgurio_media_library_manager.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
