parameters:
#    fulgurio_media_library_manager.example.class: Fulgurio\MediaLibraryManagerBundle\Example

services:
    fulgurio_media_library_manager.twig.extension:
        class: Fulgurio\MediaLibraryManagerBundle\Extension\AmazonTwigExtension
        arguments:
            container: "@service_container"
        tags:
            -  { name: twig.extension }
