<?php

namespace Fulgurio\MediaLibraryManagerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MusicAlbumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MusicAlbumRepository extends EntityRepository
{
    /**
     * Number of album per page
     * @var integer
     */
    const NB_PER_PAGE = 1;

    /**
     * Get music album with pagination
     *
     * @param Paginator $paginator KNPPaginator
     * @param integer $page Current page
     */
    public function findWithPaginator($paginator, $page)
    {
        $query = $this->getEntityManager()->createQuery('SELECT ma FROM FulgurioMediaLibraryManagerBundle:MusicAlbum ma ORDER BY ma.artist DESC');
        return ($paginator->paginate($query, $page, self::NB_PER_PAGE));
    }
}
