<?php

namespace Fulgurio\MediaLibraryManagerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MusicAlbumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MusicAlbumRepository extends EntityRepository
{
    /**
     * Number of album per page
     * @var integer
     * @todo : put the value into config
     */
    const NB_PER_PAGE = 10;

    /**
     * Get music album with pagination
     *
     * @param Paginator $paginator KNPPaginator
     * @param integer $page Current page
     * @param string $filter
     */
    public function findAllWithPaginator($paginator, $page, $filter)
    {
        if (!is_null($filter) && trim($filter) != '')
        {
            $query = $this->getEntityManager()->createQuery('SELECT ma FROM FulgurioMediaLibraryManagerBundle:MusicAlbum ma WHERE ma.artist LIKE :artist OR ma.title LIKE :title ORDER BY ma.artist ASC, ma.title ASC');
            $query->setParameter('artist', $filter . '%');
            $query->setParameter('title', $filter . '%');
        }
        else
        {
            $query = $this->getEntityManager()->createQuery('SELECT ma FROM FulgurioMediaLibraryManagerBundle:MusicAlbum ma ORDER BY ma.artist ASC, ma.title ASC');
        }
        return ($paginator->paginate($query, $page, self::NB_PER_PAGE));
    }
}
