<?php
/*
 * This file is part of the MediaLibraryManagerBundle package.
 *
 * (c) Fulgurio <http://fulgurio.net>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Fulgurio\MediaLibraryManagerBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Knp\Component\Pager\Paginator;

/**
 * MusicAlbumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MusicAlbumRepository extends EntityRepository
{
    /**
     * Number of album per page
     * @var integer
     * @todo : put the value into config
     */
    const NB_PER_PAGE = 10;


    /**
     * Get music album with pagination
     *
     * @param Paginator $paginator KNPPaginator
     * @param integer $page Current page
     * @param string $filter
     * @return \Knp\Component\Pager\Pagination\PaginationInterface
     */
    public function findAllWithPaginator(Paginator $paginator, $page, $filter)
    {
        $qb = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('ma')
            ->from('FulgurioMediaLibraryManagerBundle:MusicAlbum', 'ma')
            ->orderBy('ma.artist', 'ASC')
            ->addOrderBy('ma.title', 'ASC');
        if (!is_null($filter) && trim($filter) != '')
        {
            $qb->where('ma.artist LIKE :artist')
                ->orWhere('ma.title LIKE :title')
                ->setParameter('artist', $filter . '%')
                ->setParameter('title', $filter . '%');
        }

        return $paginator->paginate($qb->getQuery(), $page, self::NB_PER_PAGE);
    }
}
