Fulgurio\MediaLibraryManagerBundle\Entity\MusicAlbum:
    constraints:
        - Callback:         [validate]
    properties:
        title:
            - NotBlank:
                message:    music.title.not_blank
            - Length:
                max:        128
                maxMessage: music.title.max_length
        artist:
            - Length:
                max:        128
                maxMessage: music.author.max_length
        ean:
            - Length:
                max:        13
                maxMessage: music.ean.max_length
        publisher:
            - Length:
                max:        32
                maxMessage: music.publisher.max_length
