FulgurioMLM_Music_Retrieve_Album_Infos:
    pattern:  /retrieve_album_infos
    defaults: { _controller: FulgurioMediaLibraryManagerBundle:Music:retrieveAlbumInfos }

FulgurioMLM_Music_Retrieve_Track_Lyrics:
    pattern:  /retrieve_lyrics_track
    defaults: { _controller: FulgurioMediaLibraryManagerBundle:Music:retrieveLyricsTrack }


FulgurioMLM_Music_Add:
    pattern:  /add
    defaults: { _controller: FulgurioMediaLibraryManagerBundle:Music:add }

FulgurioMLM_Music_Edit:
    pattern:  /{albumId}/edit
    defaults: { _controller: FulgurioMediaLibraryManagerBundle:Music:add }
    
FulgurioMLM_Music_Remove:
    pattern:  /{albumId}/remove
    defaults: { _controller: FulgurioMediaLibraryManagerBundle:Music:remove }

FulgurioMLM_Music_List:
    pattern:  /
    defaults: { _controller: FulgurioMediaLibraryManagerBundle:Music:list }
