FulgurioMLM_Music_Retrieve_Album_Infos:
    path:  /retrieve_album_infos
    defaults: { _controller: FulgurioMediaLibraryManagerBundle:Music:retrieveAlbumInfos }

FulgurioMLM_Music_Retrieve_Track_Lyrics:
    path:  /retrieve_lyrics_track
    defaults: { _controller: FulgurioMediaLibraryManagerBundle:Music:retrieveLyricsTrack }

FulgurioMLM_Music_Add:
    path:  /add
    defaults: { _controller: FulgurioMediaLibraryManagerBundle:Music:add }

FulgurioMLM_Music_Edit:
    path:  /{albumId}/edit
    defaults: { _controller: FulgurioMediaLibraryManagerBundle:Music:add }

FulgurioMLM_Music_Remove:
    path:  /{albumId}/remove
    defaults: { _controller: FulgurioMediaLibraryManagerBundle:Music:remove }

FulgurioMLM_Music_List:
    path:  /
    defaults: { _controller: FulgurioMediaLibraryManagerBundle:Music:list }
